const express = require('express');
const router = express.Router();
const app = express();
app.use(express.json());
router.get('/', (request, response) => response.json({message:'Basic route'}));
router.get('/items/:id', (request, response) => response.json({id:request.params.id, query:request.query}));
router.get('/users', (request, response) => response.json({route:'users'}));
router.get('/products', (request, response) => response.json({route:'products'}));
router.use((request, response) => response.status(404).json({error:'Not Found'}));
app.use('/api', router);
app.listen(3000, () => console.log('Routing server on http://localhost:3000/api'));